# Generated by Django 5.1.4 on 2025-04-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='celular',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='documento_identidad',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='es_pep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('viudo', 'Viudo'), ('divorciado', 'Divorciado'), ('union_libre', 'Unión Libre')], default='soltero', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(default='peru', max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ocupacion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_documento',
            field=models.CharField(choices=[('dni', 'DNI'), ('ce', 'Carné de extranjería'), ('pasaporte', 'Pasaporte')], default='dni', max_length=50),
        ),
    ]
