# Generated by Django 5.1.4 on 2025-04-28 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfil_telefono_remove_perfil_tipo_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('CRYPTO_TO_FIAT', 'Crypto a Fiat'), ('FIAT_TO_CRYPTO', 'Fiat a Crypto')], max_length=15)),
                ('moneda_origen', models.CharField(max_length=4)),
                ('cantidad_origen', models.DecimalField(decimal_places=6, max_digits=16)),
                ('moneda_destino', models.CharField(max_length=4)),
                ('cantidad_destino', models.DecimalField(decimal_places=6, max_digits=16)),
                ('tasa_cambio', models.DecimalField(decimal_places=6, max_digits=16)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('hash_transaccion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
