# Generated by Django 5.1.4 on 2025-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='hash_transaccion',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='constancia_archivo',
            field=models.FileField(blank=True, null=True, upload_to='constancias/'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cantidad_destino',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='cantidad_origen',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='moneda_destino',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='moneda_origen',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo_operacion',
            field=models.CharField(choices=[('CRYPTO_TO_FIAT', 'Cripto a Soles/Dólares'), ('FIAT_TO_CRYPTO', 'Soles/Dólares a Cripto')], max_length=20),
        ),
    ]
