# Generated by Django 5.1.4 on 2025-04-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_transaccion_hash_transaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banco',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cuenta_bancaria',
            field=models.CharField(default='', max_length=100),
        ),
    ]
