# Generated by Django 5.1.4 on 2025-05-18 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfil_direccion_wallet_perfil_red_wallet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(choices=[('', 'Seleccionar país'), ('argentina', 'Argentina'), ('bolivia', 'Bolivia'), ('brasil', 'Brasil'), ('chile', 'Chile'), ('colombia', 'Colombia'), ('costa_rica', 'Costa Rica'), ('cuba', 'Cuba'), ('ecuador', 'Ecuador'), ('el_salvador', 'El Salvador'), ('guatemala', 'Guatemala'), ('haiti', 'Haití'), ('honduras', 'Honduras'), ('mexico', 'México'), ('nicaragua', 'Nicaragua'), ('panama', 'Panamá'), ('paraguay', 'Paraguay'), ('peru', 'Perú'), ('republica_dominicana', 'República Dominicana'), ('uruguay', 'Uruguay'), ('venezuela', 'Venezuela')], default='Perú', max_length=50),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('BCP', 'Banco de Crédito del Perú'), ('INTERBANK', 'Interbank')], max_length=50)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(choices=[('TRC20', 'Trc-20'), ('BINANCE', 'Binance PAY')], max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
