# Generated by Django 5.1.4 on 2025-05-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_perfil_nacionalidad_cuentabancaria_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cuenta_bancaria',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='direccion_wallet',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='red_wallet',
        ),
    ]
