# Generated by Django 5.1.4 on 2025-05-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_perfil_banco_remove_perfil_cuenta_bancaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='moneda',
            field=models.CharField(choices=[('PEN', 'Soles (PEN)'), ('USD', 'Dólares (USD)')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='tipo_cuenta',
            field=models.CharField(choices=[('AHO', 'Ahorros'), ('COR', 'Corriente')], default='AHO', max_length=3),
        ),
    ]
