# Generated by Django 5.1.4 on 2025-05-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_cuentabancaria_moneda_cuentabancaria_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='moneda',
            field=models.CharField(choices=[('PEN', 'PEN'), ('USD', 'USD')], default='PEN', max_length=3),
        ),
    ]
