# Generated by Django 5.1.4 on 2025-05-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_cuentabancaria_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(choices=[('TRC', 'TRC-20'), ('ERC', 'ERC-20'), ('BEP', 'BEP-20')], max_length=10)),
                ('direccion', models.CharField(max_length=100, unique=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
