# Generated by Django 5.1.4 on 2025-05-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_walletempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletempresa',
            name='moneda',
            field=models.CharField(choices=[('USDT', 'USDT'), ('USDC', 'USDC')], default='USDT', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletempresa',
            name='principal',
            field=models.BooleanField(default=False, help_text='Marca esta wallet como principal para recibir depósitos.'),
        ),
        migrations.AlterField(
            model_name='walletempresa',
            name='red',
            field=models.CharField(choices=[('TRC', 'TRC-20'), ('ERC', 'ERC-20'), ('BEP', 'BEP-20')], max_length=20),
        ),
    ]
