# Generated by Django 5.1.4 on 2025-05-22 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_walletempresa_moneda_walletempresa_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='wallet_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.walletempresa'),
        ),
    ]
