# Generated by Django 5.1.4 on 2025-05-22 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_cuentaempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cuenta_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='usuarios.cuentaempresa'),
        ),
    ]
