# Generated by Django 5.1.4 on 2025-05-22 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_transaccion_cuenta_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.wallet'),
        ),
    ]
