# Generated by Django 5.1.4 on 2025-05-29 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_transaccion_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='usuarios.cuentabancaria'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('INICIADO', 'Iniciado'), ('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('FACTURADA', 'Facturada'), ('RECHAZADO', 'Rechazado')], default='INICIADO', max_length=20),
        ),
    ]
