# Generated by Django 5.1.4 on 2025-05-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_transaccion_cuenta_bancaria_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='cci',
            field=models.CharField(blank=True, help_text='Código de Cuenta Interbancario', max_length=20, null=True),
        ),
    ]
