# Generated by Django 5.1.4 on 2025-05-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_cuentabancaria_cci'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='moneda',
            field=models.CharField(choices=[('USDT', 'USDT (Tether)'), ('USDC', 'USDC (USD Coin)')], default='USDT', max_length=10),
        ),
    ]
