# Generated by Django 5.1.4 on 2025-05-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_wallet_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cambio_password_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='codigo_verificacion_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
