# Generated by Django 5.1.4 on 2025-05-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_perfil_cambio_password_verificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigo_verificacion_email',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='codigo_verificacion_email_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
