# Generated by Django 5.1.4 on 2025-06-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_perfil_codigo_verificacion_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.AddField(
            model_name='wallet',
            name='estado_riesgo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Verificación'), ('OPERATIVO', 'Operativo'), ('RIESGO', 'Riesgo Detectado'), ('NO_EXISTE', 'No Existe')], default='PENDIENTE', help_text='Estado de riesgo de la wallet', max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='ultima_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='red',
            field=models.CharField(choices=[('TRX', 'TRON (TRC-20)'), ('ETH', 'Ethereum (ERC-20)'), ('SOL', 'Solana')], max_length=20),
        ),
    ]
