# Generated by Django 5.1.4 on 2025-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_wallet_options_wallet_estado_riesgo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='didit_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='didit_session_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_verificacion_didit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='resultado_verificacion_didit',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='perfil',
            name='verificacion_didit_completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='verificacion_didit_requerida',
            field=models.BooleanField(default=True),
        ),
    ]
