# Generated by Django 5.1.4 on 2025-06-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_perfil_didit_session_id_perfil_didit_session_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='didit_session_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
