# Generated by Django 5.1.4 on 2025-06-08 16:21

import usuarios.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_alter_perfil_didit_session_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(choices=[('', 'Seleccionar país'), ('argentina', 'Argentina'), ('bolivia', 'Bolivia'), ('brasil', 'Brasil'), ('chile', 'Chile'), ('colombia', 'Colombia'), ('costa_rica', 'Costa Rica'), ('cuba', 'Cuba'), ('ecuador', 'Ecuador'), ('el_salvador', 'El Salvador'), ('guatemala', 'Guatemala'), ('haiti', 'Haití'), ('honduras', 'Honduras'), ('mexico', 'México'), ('nicaragua', 'Nicaragua'), ('panama', 'Panamá'), ('paraguay', 'Paraguay'), ('peru', 'Perú'), ('republica_dominicana', 'República Dominicana'), ('uruguay', 'Uruguay'), ('venezuela', 'Venezuela')], default='peru', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='constancia_archivo',
            field=models.FileField(blank=True, help_text='Comprobante de la transacción (PDF, JPG, PNG)', null=True, storage=usuarios.storage.ConstanciasStorage(), upload_to=usuarios.storage.constancia_upload_path),
        ),
    ]
