# Generated by Django 5.1.4 on 2025-06-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_add_s3_storage_for_constancias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletempresa',
            name='red',
            field=models.CharField(choices=[('TRC', 'TRC-20'), ('ERC', 'ERC-20'), ('BEP', 'BEP-20'), ('BINANCE_PAY', 'Binance Pay')], max_length=20),
        ),
    ]
