# Generated by Django 5.1.4 on 2025-06-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_alter_walletempresa_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='red',
            field=models.CharField(choices=[('TRX', 'TRON (TRC-20)'), ('ETH', 'Ethereum (ERC-20)'), ('SOL', 'Solana'), ('BINANCE_PAY', 'Binance Pay')], max_length=20),
        ),
    ]
