# Generated by Django 5.1.4 on 2025-05-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platea', '0002_exchangerate_created_at_exchangerate_rate_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='rate',
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate_compra',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate_venta',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
            preserve_default=False,
        ),
    ]
