# Generated by Django 5.1.4 on 2025-05-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platea', '0003_remove_exchangerate_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_from',
            field=models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('USDT', 'USDT'), ('USDC', 'USDC'), ('PEN', 'Nuevo Sol Peruano')], max_length=4),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_to',
            field=models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('USDT', 'USDT'), ('USDC', 'USDC'), ('PEN', 'Nuevo Sol Peruano')], max_length=4),
        ),
    ]
